micronaut:
  application:
    name: Ruby Kurosawa

  metrics:
    enabled: ${metrics.enabled:true}
    export:
      influx:
        enabled: true
        uri: ${influx.uri:`http://localhost:8086`}
        org: ${influx.org:zettai-yain}
        bucket: ${influx.bucket:ruby_kurosawa}
        token: ${influx.token}

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: ${postgres.url:`jdbc:postgresql://localhost:5432/ruby_kurosawa`}
    driverClassName: org.postgresql.Driver
    username: ${postgres.username:ruby_kurosawa}
    password: ${postgres.password:ruby_kurosawa}
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none

flyway:
  datasources:
    default:
      enabled: true
