micronaut:
  application:
    name: ruby

  ssl:
    enabled: false
    build-self-signed: true

  server:
    netty:
      access-logger:
        enabled: true

  metrics:
    enabled: true
    export:
      influx:
        enabled: false

  security:
    enabled: false
    basic-auth:
      enabled: true
      credentials:
        username: test
        password: test123

    intercept-url-map:
      - pattern: /swagger/**
        access: ["isAnonymous()"]
      - pattern: /swagger-ui/**
        access: ["isAnonymous()"]

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'password'
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none

flyway:
  datasources:
    default:
      enabled: true
