micronaut:
  application:
    name: Ruby Kurosawa

  metrics:
    enabled: true
    export:
      influx:
        enabled: false

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'password'
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none

flyway:
  datasources:
    default:
      enabled: true
